In [49]:
import pandas as pd
import sklearn
import matplotlib as plt

In [50]:
df_old = pd.read_csv('merged_data_16_24.csv', low_memory=False)

In [51]:
df_25 = pd.read_csv('merged_gw_24_25.csv', low_memory=False, on_bad_lines='skip')

In [52]:
df_current = pd.read_csv('merged_gw_25-26_gw9.csv', low_memory=False)

In [53]:
df_old.head()

,season_x,name,position,team_x,assists,bonus,bps,clean_sheets,creativity,element,...,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,2016-17,Aaron Cresswell,DEF,NaN,0,0,0,0,0.0,454,...,2,0,0,0,0,0,55,False,0,1
1,2016-17,Aaron Lennon,MID,NaN,0,0,6,0,0.3,142,...,1,0,1,0,0,0,60,True,0,1
2,2016-17,Aaron Ramsey,MID,NaN,0,0,5,0,4.9,16,...,3,23,2,0,0,0,80,True,0,1
3,2016-17,Abdoulaye Doucouré,MID,NaN,0,0,0,0,0.0,482,...,1,0,0,0,0,0,50,False,0,1
4,2016-17,Abdul Rahman Baba,DEF,NaN,0,0,0,0,0.0,80,...,2,0,0,0,0,0,55,True,0,1

In [54]:
df_25.head()

,name,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,...,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,Alex Scott,MID,Bournemouth,1.6,0,0,11,0,12.8,77,...,1,0.0,2,0,0,0,50,False,0,1
1,Carlos Miguel dos Santos Pereira,GK,Nott'm Forest,2.2,0,0,0,0,0.0,427,...,1,0.0,0,0,0,0,45,True,0,1
2,Tomiyasu Takehiro,DEF,Arsenal,0.0,0,0,0,0,0.0,22,...,2,0.0,0,0,0,0,50,True,0,1
3,Malcolm Ebiowei,MID,Crystal Palace,0.0,0,0,0,0,0.0,197,...,2,0.0,0,0,0,0,45,False,0,1
4,Ben Brereton Díaz,MID,Southampton,1.0,0,0,-2,0,14.0,584,...,1,16.0,1,0,0,0,55,False,1,1

In [25]:
df_current.head()

,name,position,team,xP,assists,bonus,bps,clean_sheets,clearances_blocks_interceptions,creativity,...,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,Elliot Anderson,MID,Nott'm Forest,2.0,1,1,24,0,1,21.3,...,3,20.0,6,0,0,0,55,True,0,1
1,James Tarkowski,DEF,Everton,3.8,0,0,7,0,13,2.1,...,1,7.0,4,0,0,0,55,False,0,1
2,Ollie Watkins,FWD,Aston Villa,2.3,0,0,12,1,2,12.2,...,0,27.0,2,0,0,0,90,True,0,1
3,Iliman Ndiaye,MID,Everton,2.7,0,0,11,0,1,12.1,...,1,2.0,2,0,0,0,65,False,0,1
4,Charalampos Kostoulas,FWD,Brighton,1.4,0,0,0,0,0,0.0,...,1,0.0,0,0,0,0,50,True,0,1

In [55]:
df_old.columns

Index(['season_x', 'name', 'position', 'team_x', 'assists', 'bonus', 'bps',
       'clean_sheets', 'creativity', 'element', 'fixture', 'goals_conceded',
       'goals_scored', 'ict_index', 'influence', 'kickoff_time', 'minutes',
       'opponent_team', 'opp_team_name', 'own_goals', 'penalties_missed',
       'penalties_saved', 'red_cards', 'round', 'saves', 'selected',
       'team_a_score', 'team_h_score', 'threat', 'total_points',
       'transfers_balance', 'transfers_in', 'transfers_out', 'value',
       'was_home', 'yellow_cards', 'GW'],
      dtype='object')

In [29]:
df_25.columns

Index(['name', 'position', 'team', 'xP', 'assists', 'bonus', 'bps',
       'clean_sheets', 'creativity', 'element', 'expected_assists',
       'expected_goal_involvements', 'expected_goals',
       'expected_goals_conceded', 'fixture', 'goals_conceded', 'goals_scored',
       'ict_index', 'influence', 'kickoff_time', 'minutes', 'modified',
       'opponent_team', 'own_goals', 'penalties_missed', 'penalties_saved',
       'red_cards', 'round', 'saves', 'selected', 'starts', 'team_a_score',
       'team_h_score', 'threat', 'total_points', 'transfers_balance',
       'transfers_in', 'transfers_out', 'value', 'was_home', 'yellow_cards',
       'GW'],
      dtype='object')

In [56]:

df_current.columns

Index(['name', 'position', 'team', 'xP', 'assists', 'bonus', 'bps',
       'clean_sheets', 'clearances_blocks_interceptions', 'creativity',
       'defensive_contribution', 'element', 'expected_assists',
       'expected_goal_involvements', 'expected_goals',
       'expected_goals_conceded', 'fixture', 'goals_conceded', 'goals_scored',
       'ict_index', 'influence', 'kickoff_time', 'minutes', 'modified',
       'opponent_team', 'own_goals', 'penalties_missed', 'penalties_saved',
       'recoveries', 'red_cards', 'round', 'saves', 'selected', 'starts',
       'tackles', 'team_a_score', 'team_h_score', 'threat', 'total_points',
       'transfers_balance', 'transfers_in', 'transfers_out', 'value',
       'was_home', 'yellow_cards', 'GW'],
      dtype='object')

In [57]:
# Fixing the DATASETS renaming and peprare to combine

In [58]:
df_old.rename(columns={'team_x': 'team', 'season_x': 'season'}, inplace=True)

In [59]:
df_25['season'] = '2024-25'
df_current['season'] = '2025-26'

In [60]:
df_old.columns

Index(['season', 'name', 'position', 'team', 'assists', 'bonus', 'bps',
       'clean_sheets', 'creativity', 'element', 'fixture', 'goals_conceded',
       'goals_scored', 'ict_index', 'influence', 'kickoff_time', 'minutes',
       'opponent_team', 'opp_team_name', 'own_goals', 'penalties_missed',
       'penalties_saved', 'red_cards', 'round', 'saves', 'selected',
       'team_a_score', 'team_h_score', 'threat', 'total_points',
       'transfers_balance', 'transfers_in', 'transfers_out', 'value',
       'was_home', 'yellow_cards', 'GW'],
      dtype='object')

In [61]:
df_25.columns

Index(['name', 'position', 'team', 'xP', 'assists', 'bonus', 'bps',
       'clean_sheets', 'creativity', 'element', 'expected_assists',
       'expected_goal_involvements', 'expected_goals',
       'expected_goals_conceded', 'fixture', 'goals_conceded', 'goals_scored',
       'ict_index', 'influence', 'kickoff_time', 'minutes', 'modified',
       'opponent_team', 'own_goals', 'penalties_missed', 'penalties_saved',
       'red_cards', 'round', 'saves', 'selected', 'starts', 'team_a_score',
       'team_h_score', 'threat', 'total_points', 'transfers_balance',
       'transfers_in', 'transfers_out', 'value', 'was_home', 'yellow_cards',
       'GW', 'season'],
      dtype='object')

In [62]:
df_current.columns

Index(['name', 'position', 'team', 'xP', 'assists', 'bonus', 'bps',
       'clean_sheets', 'clearances_blocks_interceptions', 'creativity',
       'defensive_contribution', 'element', 'expected_assists',
       'expected_goal_involvements', 'expected_goals',
       'expected_goals_conceded', 'fixture', 'goals_conceded', 'goals_scored',
       'ict_index', 'influence', 'kickoff_time', 'minutes', 'modified',
       'opponent_team', 'own_goals', 'penalties_missed', 'penalties_saved',
       'recoveries', 'red_cards', 'round', 'saves', 'selected', 'starts',
       'tackles', 'team_a_score', 'team_h_score', 'threat', 'total_points',
       'transfers_balance', 'transfers_in', 'transfers_out', 'value',
       'was_home', 'yellow_cards', 'GW', 'season'],
      dtype='object')

In [63]:
# keeping only the must have columns

In [64]:
common_columns = ['name', 'position', 'team', 'season', 'GW',
                 'minutes', 'total_points', 'value', 'selected',
                 'goals_scored', 'assists', 'clean_sheets', 'goals_conceded',
                 'own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards', 'red_cards',
                  'saves', 'bonus', 'bps', 'influence', 'creativity', 'threat', 'ict_index',
                  'transfers_balance', 'transfers_in', 'transfers_out',
                  'team_h_score', 'team_a_score', 'was_home', 'opponent_team', 'fixture', 'round', 'element'
                 ]

In [65]:
# Filtering and merging

In [66]:
df_part1 = df_old[common_columns]
df_part2 = df_25[common_columns]
df_part3 = df_current[common_columns]

In [74]:
final_df = pd.concat([df_part1, df_part2, df_part3], axis=0, ignore_index=True)

In [75]:
# Filtering out the old seasons

In [76]:
seasons_to_keep = ['2021-22', '2022-23', '2023-24', '2024-25', '2025-26']

In [78]:
final_df = final_df[final_df['season'].isin(seasons_to_keep)]

In [79]:
#exporting and saving the new file

In [81]:
final_df.to_csv('final_fpl_dataset.csv', index=False)
print(f"Sucess! {len(final_df)} rows.")
print("columns:", list(final_df.columns))

Sucess! 101676 rows.
columns: ['name', 'position', 'team', 'season', 'GW', 'minutes', 'total_points', 'value', 'selected', 'goals_scored', 'assists', 'clean_sheets', 'goals_conceded', 'own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards', 'red_cards', 'saves', 'bonus', 'bps', 'influence', 'creativity', 'threat', 'ict_index', 'transfers_balance', 'transfers_in', 'transfers_out', 'team_h_score', 'team_a_score', 'was_home', 'opponent_team', 'fixture', 'round', 'element']